export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL=' PRODUCT_LIST_FAIL';


export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL=' PRODUCT_DETAILS_FAIL';


export const ADD_TO_COMMENT_REQUEST ='ADD_TO_COMMENT_REQUEST';
export const ADD_TO_COMMENT_SUCCESS ='ADD_TO_COMMENT_SUCCESS';
export const ADD_TO_COMMENT_FAIL ='ADD_TO_COMMENT_FAIL';

export const GET_COMMENT_REQUEST ='GET_COMMENT_REQUEST';
export const GET_COMMENT_SUCCESS ='GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAIL ='GET_COMMENT_FAIL';


export const ADD_NEW_PRODUCT_REQUEST= 'ADD_NEW_PRODUCT_REQUEST';
export const ADD_NEW_PRODUCT_SUCCESS ='ADD_NEW_PRODUCT_SUCCESS';
export const ADD_NEW_PRODUCT_FAIL ='ADD_NEW_PRODUCT_FAIL';


export const ADD_PRODUCT_REVIEW_REQUEST ='ADD_PRODUCT_REVIEW_REQUEST';
export const ADD_PRODUCT_REVIEW_SUCCESS= 'ADD_PRODUCT_REVIEW_SUCCESS';
export const ADD_PRODUCT_REVIEW_FAIL ='ADD_PRODUCT_REVIEW_FAIL';
export const ADD_PRODUCT_REVIEW_RESET ='ADD_PRODUCT_REVIEW_RESET';

export const GET_PRODUCT_REVIEW_REQUEST='GET_PRODUCT_REVIEW_REQUEST';
export const GET_PRODUCT_REVIEW_SUCCESS ='GET_PRODUCT_REVIEW_SUCCESS';
export const GET_PRODUCT_REVIEW_FAIL ='GET_PRODUCT_REVIEW_FAIL';