export const USER_SIGNIN_REQUEST='USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS='USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL='USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL';
export const USER_SIGNOUT='USER_SIGNOUT';

export const USER_DETAILS_REQUEST='USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS='USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL='USER_DETAILS_FAIL';


export const USER_UPDATE_PROFILE_REQUEST='USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS='USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL='USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET='USER_UPDATE_PROFILE_RESET';


export const USER_LIST_REQUEST='USER_LIST_REQUEST';
export const USER_LIST_SUCCESS='USER_LIST_SUCCESS';
export const USER_LIST_FAIL='USER_LIST_FAIL';

export const SEND_EMAIL_REQUEST='SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS='SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAIL='SEND_EMAIL_FAIL';


export const SEND_EMAIL_FOR_OTP_REQUEST='SEND_EMAIL_FOR_OTP_REQUEST';
export const SEND_EMAIL_FOR_OTP_SUCCESS='SEND_EMAIL_FOR_OTP_SUCCESS';
export const SEND_EMAIL_FOR_OTP_FAIL='SEND_EMAIL_FOR_OTP_FAIL';


export const CHANGE_PASSWORD_REQUEST='CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS ='CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL='CHANGE_PASSWORD_FAIL';

export const RESET_CHANGE_PASSWORD='RESET_CHANGE_PASSWORD';

